// This is autogenerated, please modify predeploy.js to change this
module.exports = {
  "v86state.bin":
    "https://storage.googleapis.com/hypertalk-static/v86state.bin",
  "windows98.img":
    "https://storage.googleapis.com/hypertalk-static/windows98.img"
}
